import type { Metadata } from "next";
import { gochi, splash, bree } from "@/lib/fonts";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import ClickSpark from "@/components/ui/ClickSpark";
import { COLORS } from "@/lib/colors";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Portfolio | Angadveer Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body
        className={`flex min-h-full flex-col ${gochi.variable} ${splash.variable} ${bree.variable}`}
      >
        <ClickSpark
          sparkColor={COLORS.primary}
          sparkSize={12}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
