import type { Metadata } from "next";
import { gochi, splash, bree } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portfolio | Angadveer Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${gochi.variable} ${splash.variable} ${bree.variable}`}>{children}</body>
    </html>
  );
}
